### PR TITLE
Fixed projects list in analyze.py

### PR DESCRIPTION
**Pull request by ethanbwang**

### CODE REVIEW

**Comment by ethanbwang** [comment]
I just changed the list of projects I had to remove cjson and I also added lua since lua is a C project. Looks like git is marking that as a conflict, do I need to fix it on my end?

**Comment by EYH0602** [comment]
> I just changed the list of projects I had to remove cjson and I also added lua since lua is a C project. Looks like git is marking that as a conflict, do I need to fix it on my end?

you can use `git rebase hyf-dev` on your end, or use click on the "Resolve conflicts" to do this online

**Review by EYH0602 — APPROVED** [review]

**Comment by ethanbwang** [comment]
I think resolving the conflict in the browser is causing the extra merge commit

**Comment by EYH0602** [comment]
> I think resolving the conflict in the browser is causing the extra merge commit. Doing the rebase on my end wasn't letting me change the pull request here I'm not sure why.

the conflict is solved now,

**Pull request merged**
